import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

const baseline = readFileSync(resolve(process.cwd(), 'db/postgres/migrations/0001_baseline.sql'), 'utf8');

describe('PostgreSQL baseline migration', () => {
  it('contains the complete application schema and migration marker', () => {
    expect((baseline.match(/CREATE TABLE IF NOT EXISTS/g) ?? []).length).toBe(52);
    expect(baseline).toContain('CREATE TABLE IF NOT EXISTS app_job_lock');
    expect(baseline).toContain('CREATE TABLE IF NOT EXISTS schema_migration');
    expect(baseline).toContain("VALUES ('0001_baseline'");
  });

  it('uses PostgreSQL-safe integer and identity types', () => {
    expect(baseline).toContain('BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
    expect(baseline).not.toMatch(/\bINTEGER\b/);
    expect(baseline).not.toContain('AUTOINCREMENT');
  });

  it('does not retain SQLite-only schema syntax', () => {
    expect(baseline).not.toContain('COLLATE NOCASE');
    expect(baseline).not.toContain('sqlite_sequence');
    expect(baseline).not.toContain('sqlite_master');
  });
});
