-- Generated by scripts/generate-postgres-baseline.mjs.
-- Source schema is read-only; review this migration before production use.
BEGIN;

CREATE TABLE IF NOT EXISTS vn (
      id              TEXT PRIMARY KEY,
      title           TEXT NOT NULL,
      alttitle        TEXT,
      image_url       TEXT,
      image_thumb     TEXT,
      released        TEXT,
      olang           TEXT,
      languages       TEXT,
      platforms       TEXT,
      length_minutes  BIGINT,
      length          BIGINT,
      rating          DOUBLE PRECISION,
      votecount       BIGINT,
      description     TEXT,
      developers      TEXT,
      tags            TEXT,
      raw             TEXT,
      fetched_at      BIGINT NOT NULL, screenshots TEXT, image_sexual DOUBLE PRECISION, image_violence DOUBLE PRECISION, local_image TEXT, local_image_thumb TEXT, custom_cover TEXT, release_images TEXT, banner_image TEXT, banner_position TEXT, relations TEXT, egs_only BIGINT NOT NULL DEFAULT 0, aliases TEXT, extlinks TEXT, length_votes BIGINT, average DOUBLE PRECISION, has_anime BIGINT, editions TEXT, staff TEXT, va TEXT, devstatus BIGINT, titles TEXT, publishers TEXT, cover_rotation BIGINT NOT NULL DEFAULT 0, banner_rotation BIGINT NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS collection (
      vn_id            TEXT PRIMARY KEY REFERENCES vn(id) ON DELETE CASCADE,
      status           TEXT NOT NULL DEFAULT 'planning',
      user_rating      BIGINT,
      playtime_minutes BIGINT NOT NULL DEFAULT 0,
      started_date     TEXT,
      finished_date    TEXT,
      notes            TEXT,
      favorite         BIGINT NOT NULL DEFAULT 0,
      added_at         BIGINT NOT NULL,
      updated_at       BIGINT NOT NULL, location TEXT NOT NULL DEFAULT 'unknown', edition_type TEXT NOT NULL DEFAULT 'none', edition_label TEXT, physical_location TEXT, box_type TEXT NOT NULL DEFAULT 'none', download_url TEXT, dumped BIGINT NOT NULL DEFAULT 0, source_pref TEXT, custom_order BIGINT NOT NULL DEFAULT 0, custom_description TEXT, dumped_ignored BIGINT NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS producer (
      id          TEXT PRIMARY KEY,
      name        TEXT NOT NULL,
      original    TEXT,
      lang        TEXT,
      type        TEXT,
      description TEXT,
      aliases     TEXT,
      extlinks    TEXT,
      logo_path   TEXT,
      fetched_at  BIGINT NOT NULL
    );
CREATE TABLE IF NOT EXISTS series (
      id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name        TEXT NOT NULL UNIQUE,
      description TEXT,
      cover_path  TEXT,
      created_at  BIGINT NOT NULL,
      updated_at  BIGINT NOT NULL, banner_path TEXT);
CREATE TABLE IF NOT EXISTS series_vn (
      series_id   BIGINT NOT NULL REFERENCES series(id) ON DELETE CASCADE,
      vn_id       TEXT NOT NULL REFERENCES vn(id) ON DELETE CASCADE,
      order_index BIGINT NOT NULL DEFAULT 0,
      PRIMARY KEY (series_id, vn_id)
    );
CREATE TABLE IF NOT EXISTS vndb_cache (
      cache_key     TEXT PRIMARY KEY,
      body          TEXT NOT NULL,
      etag          TEXT,
      last_modified TEXT,
      fetched_at    BIGINT NOT NULL,
      expires_at    BIGINT NOT NULL
    );
CREATE TABLE IF NOT EXISTS owned_release (
      vn_id      TEXT NOT NULL REFERENCES vn(id) ON DELETE CASCADE,
      release_id TEXT NOT NULL,
      notes      TEXT,
      added_at   BIGINT NOT NULL, location TEXT NOT NULL DEFAULT 'unknown', physical_location TEXT, box_type TEXT NOT NULL DEFAULT 'none', edition_label TEXT, condition TEXT, price_paid DOUBLE PRECISION, currency TEXT, acquired_date TEXT, dumped BIGINT NOT NULL DEFAULT 0, purchase_place TEXT, owned_platform TEXT, cover_rotation BIGINT NOT NULL DEFAULT 0,
      PRIMARY KEY (vn_id, release_id)
    );
CREATE TABLE IF NOT EXISTS vn_route (
      id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      vn_id          TEXT NOT NULL REFERENCES vn(id) ON DELETE CASCADE,
      name           TEXT NOT NULL,
      completed      BIGINT NOT NULL DEFAULT 0,
      completed_date TEXT,
      order_index    BIGINT NOT NULL DEFAULT 0,
      notes          TEXT,
      created_at     BIGINT NOT NULL,
      updated_at     BIGINT NOT NULL
    );
CREATE TABLE IF NOT EXISTS character_image (
      char_id    TEXT PRIMARY KEY,
      url        TEXT,
      local_path TEXT,
      fetched_at BIGINT NOT NULL
    );
CREATE TABLE IF NOT EXISTS egs_game (
      vn_id      TEXT PRIMARY KEY REFERENCES vn(id) ON DELETE CASCADE,
      egs_id     BIGINT,
      gamename   TEXT,
      median     DOUBLE PRECISION,
      average    DOUBLE PRECISION,
      dispersion DOUBLE PRECISION,
      count      BIGINT,
      sellday    TEXT,
      playtime_median_minutes BIGINT,
      source     TEXT,
      fetched_at BIGINT NOT NULL, gamename_furigana TEXT, brand_id BIGINT, brand_name TEXT, model TEXT, description TEXT, image_url TEXT, local_image TEXT, okazu BIGINT, erogame BIGINT, raw_json TEXT);
CREATE TABLE IF NOT EXISTS app_setting (
      key   TEXT PRIMARY KEY,
      value TEXT
    );
CREATE TABLE IF NOT EXISTS vn_quote (
      quote_id        TEXT PRIMARY KEY,
      vn_id           TEXT NOT NULL REFERENCES vn(id) ON DELETE CASCADE,
      quote           TEXT NOT NULL,
      score           BIGINT NOT NULL DEFAULT 0,
      character_id    TEXT,
      character_name  TEXT,
      fetched_at      BIGINT NOT NULL
    );
CREATE TABLE IF NOT EXISTS vn_staff_credit (
      vn_id    TEXT NOT NULL REFERENCES vn(id) ON DELETE CASCADE,
      sid      TEXT NOT NULL,
      aid      BIGINT,
      eid      BIGINT,
      role     TEXT NOT NULL,
      note     TEXT,
      name     TEXT NOT NULL,
      original TEXT,
      lang     TEXT
    );
CREATE TABLE IF NOT EXISTS vn_va_credit (
      vn_id       TEXT NOT NULL REFERENCES vn(id) ON DELETE CASCADE,
      sid         TEXT NOT NULL,
      aid         BIGINT,
      c_id        TEXT NOT NULL,
      c_name      TEXT NOT NULL,
      c_original  TEXT,
      c_image_url TEXT,
      va_name     TEXT NOT NULL,
      va_original TEXT,
      va_lang     TEXT,
      note        TEXT
    );
CREATE TABLE IF NOT EXISTS vn_activity (
      id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      vn_id       TEXT NOT NULL REFERENCES vn(id) ON DELETE CASCADE,
      kind        TEXT NOT NULL,
      payload     TEXT,
      occurred_at BIGINT NOT NULL
    );
CREATE TABLE IF NOT EXISTS saved_filter (
      id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name     TEXT NOT NULL,
      params   TEXT NOT NULL,
      position BIGINT NOT NULL DEFAULT 0,
      created_at BIGINT NOT NULL
    );
CREATE TABLE IF NOT EXISTS reading_queue (
      vn_id    TEXT PRIMARY KEY REFERENCES vn(id) ON DELETE CASCADE,
      position BIGINT NOT NULL DEFAULT 0,
      added_at BIGINT NOT NULL
    );
CREATE TABLE IF NOT EXISTS reading_goal (
      year   BIGINT PRIMARY KEY,
      target BIGINT NOT NULL,
      updated_at BIGINT NOT NULL
    );
CREATE TABLE IF NOT EXISTS steam_link (
      vn_id      TEXT PRIMARY KEY REFERENCES vn(id) ON DELETE CASCADE,
      appid      BIGINT NOT NULL,
      steam_name TEXT NOT NULL,
      
      source     TEXT NOT NULL DEFAULT 'manual',
      last_synced_minutes BIGINT,
      created_at BIGINT NOT NULL,
      updated_at BIGINT NOT NULL
    );
CREATE TABLE IF NOT EXISTS vn_game_log (
      id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      vn_id        TEXT NOT NULL REFERENCES vn(id) ON DELETE CASCADE,
      note         TEXT NOT NULL,
      logged_at    BIGINT NOT NULL,
      session_minutes BIGINT,
      created_at   BIGINT NOT NULL,
      updated_at   BIGINT NOT NULL
    );
CREATE TABLE IF NOT EXISTS user_list (
      id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name        TEXT NOT NULL,
      slug        TEXT NOT NULL UNIQUE,
      description TEXT,
      color       TEXT,
      icon        TEXT,
      pinned      BIGINT NOT NULL DEFAULT 0,
      created_at  BIGINT NOT NULL,
      updated_at  BIGINT NOT NULL
    );
CREATE TABLE IF NOT EXISTS user_list_vn (
      list_id     BIGINT NOT NULL REFERENCES user_list(id) ON DELETE CASCADE,
      vn_id       TEXT NOT NULL,
      order_index BIGINT NOT NULL DEFAULT 0,
      added_at    BIGINT NOT NULL,
      note        TEXT,
      PRIMARY KEY (list_id, vn_id)
    );
CREATE TABLE IF NOT EXISTS shelf_unit (
      id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name        TEXT NOT NULL,
      cols        BIGINT NOT NULL DEFAULT 8,
      rows        BIGINT NOT NULL DEFAULT 4,
      order_index BIGINT NOT NULL DEFAULT 0,
      created_at  BIGINT NOT NULL,
      updated_at  BIGINT NOT NULL
    );
CREATE TABLE IF NOT EXISTS shelf_slot (
      shelf_id   BIGINT NOT NULL REFERENCES shelf_unit(id) ON DELETE CASCADE,
      row        BIGINT NOT NULL,
      col        BIGINT NOT NULL,
      vn_id      TEXT NOT NULL,
      release_id TEXT NOT NULL,
      placed_at  BIGINT NOT NULL,
      PRIMARY KEY (shelf_id, row, col),
      UNIQUE (vn_id, release_id),
      FOREIGN KEY (vn_id, release_id) REFERENCES owned_release(vn_id, release_id) ON DELETE CASCADE
    );
CREATE TABLE IF NOT EXISTS app_setting_audit (
      id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      key           TEXT NOT NULL,
      prior_preview TEXT,
      next_preview  TEXT,
      changed_at    BIGINT NOT NULL
    );
CREATE TABLE IF NOT EXISTS staff_credit_index (
      sid     TEXT NOT NULL,
      vn_id   TEXT NOT NULL,
      is_va   BIGINT NOT NULL DEFAULT 0,
      PRIMARY KEY (sid, vn_id, is_va)
    );
CREATE TABLE IF NOT EXISTS character_vn_index (
      character_id TEXT NOT NULL,
      vn_id        TEXT NOT NULL,
      PRIMARY KEY (character_id, vn_id)
    );
CREATE TABLE IF NOT EXISTS release_resolution_cache (
      release_id     TEXT PRIMARY KEY,
      width          BIGINT,
      height         BIGINT,
      raw_resolution TEXT,
      aspect_key     TEXT NOT NULL DEFAULT 'unknown',
      fetched_at     BIGINT NOT NULL, vn_id TEXT);
CREATE TABLE IF NOT EXISTS owned_release_aspect_override (
      vn_id      TEXT NOT NULL,
      release_id TEXT NOT NULL,
      width      BIGINT,
      height     BIGINT,
      aspect_key TEXT NOT NULL,
      note       TEXT,
      updated_at BIGINT NOT NULL,
      PRIMARY KEY (vn_id, release_id),
      FOREIGN KEY (vn_id, release_id) REFERENCES owned_release(vn_id, release_id) ON DELETE CASCADE
    );
CREATE TABLE IF NOT EXISTS shelf_display_slot (
      shelf_id   BIGINT NOT NULL REFERENCES shelf_unit(id) ON DELETE CASCADE,
      after_row  BIGINT NOT NULL,
      position   BIGINT NOT NULL,
      vn_id      TEXT NOT NULL,
      release_id TEXT NOT NULL,
      placed_at  BIGINT NOT NULL,
      PRIMARY KEY (shelf_id, after_row, position),
      UNIQUE (vn_id, release_id),
      FOREIGN KEY (vn_id, release_id) REFERENCES owned_release(vn_id, release_id) ON DELETE CASCADE
    );
CREATE TABLE IF NOT EXISTS vn_aspect_override (
      vn_id      TEXT PRIMARY KEY REFERENCES vn(id) ON DELETE CASCADE,
      aspect_key TEXT NOT NULL,
      note       TEXT,
      updated_at BIGINT NOT NULL
    );
CREATE TABLE IF NOT EXISTS vn_egs_link (
      vn_id      TEXT PRIMARY KEY REFERENCES vn(id) ON DELETE CASCADE,
      egs_id     BIGINT,
      note       TEXT,
      updated_at BIGINT NOT NULL
    );
CREATE TABLE IF NOT EXISTS egs_vn_link (
      egs_id     BIGINT PRIMARY KEY,
      vn_id      TEXT,
      note       TEXT,
      updated_at BIGINT NOT NULL
    );
CREATE TABLE IF NOT EXISTS release_meta_cache (
      release_id  TEXT PRIMARY KEY,
      vn_id       TEXT,
      title       TEXT,
      alttitle    TEXT,
      platforms   TEXT,
      languages   TEXT,
      released    TEXT,
      minage      BIGINT,
      patch       BIGINT NOT NULL DEFAULT 0,
      freeware    BIGINT NOT NULL DEFAULT 0,
      uncensored  BIGINT,
      official    BIGINT NOT NULL DEFAULT 1,
      has_ero     BIGINT NOT NULL DEFAULT 0,
      voiced      BIGINT,
      engine      TEXT,
      notes       TEXT,
      gtin        TEXT,
      catalog     TEXT,
      resolution  TEXT,
      media       TEXT,
      producers   TEXT,
      extlinks    TEXT,
      fetched_at  BIGINT NOT NULL
    );
CREATE TABLE IF NOT EXISTS user_activity (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      occurred_at BIGINT NOT NULL,
      kind TEXT NOT NULL,
      entity TEXT,
      entity_id TEXT,
      label TEXT,
      payload TEXT,
      actor TEXT NOT NULL DEFAULT 'user'
    );
CREATE TABLE IF NOT EXISTS vn_tag_index (
      vn_id    TEXT NOT NULL,
      tag_id   TEXT NOT NULL,
      spoiler  BIGINT NOT NULL DEFAULT 0,
      category TEXT, tag_name TEXT,
      PRIMARY KEY (vn_id, tag_id)
    );
CREATE TABLE IF NOT EXISTS vn_developer_index (
      vn_id       TEXT NOT NULL,
      producer_id TEXT NOT NULL,
      PRIMARY KEY (vn_id, producer_id)
    );
CREATE TABLE IF NOT EXISTS vn_publisher_index (
      vn_id       TEXT NOT NULL,
      producer_id TEXT NOT NULL,
      PRIMARY KEY (vn_id, producer_id)
    );
CREATE TABLE IF NOT EXISTS collection_place_index (
      vn_id TEXT NOT NULL REFERENCES collection(vn_id) ON DELETE CASCADE,
      place TEXT NOT NULL,
      PRIMARY KEY (vn_id, place)
    );
CREATE TABLE IF NOT EXISTS vn_language_index (
      vn_id TEXT NOT NULL,
      lang  TEXT NOT NULL,
      PRIMARY KEY (vn_id, lang)
    );
CREATE TABLE IF NOT EXISTS vn_platform_index (
      vn_id    TEXT NOT NULL,
      platform TEXT NOT NULL,
      PRIMARY KEY (vn_id, platform)
    );
CREATE TABLE IF NOT EXISTS "alicenet_stock" (
      code             TEXT PRIMARY KEY,
      title            TEXT NOT NULL,
      jan              TEXT,
      release_date     TEXT,
      list_price       TEXT,
      sale_price       TEXT,
      vn_id            TEXT,
      vn_match_source  TEXT,
      egs_id           BIGINT,
      egs_match_source TEXT,
      fetched_at       BIGINT NOT NULL DEFAULT 0,
      updated_at       BIGINT NOT NULL DEFAULT 0, vn_candidates TEXT, search_title TEXT, last_matched_at BIGINT, egs_title TEXT, egs_brand TEXT, egs_release_date TEXT, egs_image_url TEXT, egs_vndb_raw TEXT);
CREATE TABLE IF NOT EXISTS vn_stock_offer (
      vn_id             TEXT NOT NULL,
      provider          TEXT NOT NULL,
      provider_offer_id TEXT NOT NULL,
      source            TEXT NOT NULL,
      title             TEXT NOT NULL,
      url               TEXT NOT NULL,
      price             BIGINT,
      currency          TEXT NOT NULL DEFAULT 'JPY',
      availability      TEXT NOT NULL,
      availability_label TEXT,
      condition         TEXT,
      edition_label     TEXT,
      location_label    TEXT,
      source_release_id TEXT,
      jan               TEXT,
      fetched_at        BIGINT NOT NULL,
      updated_at        BIGINT NOT NULL,
      error             TEXT, location_branch TEXT, content_kind TEXT, platform TEXT, edition_kind TEXT, series_relation TEXT, match_confidence TEXT, match_score BIGINT, match_warnings_json TEXT, marketplace_price BIGINT, marketplace_count BIGINT, list_price BIGINT, category TEXT, store_code TEXT, product_id TEXT, page_kind TEXT,
      PRIMARY KEY (vn_id, provider, provider_offer_id)
    );
CREATE TABLE IF NOT EXISTS vn_stock_provider_status (
      vn_id      TEXT NOT NULL,
      provider   TEXT NOT NULL,
      status     TEXT NOT NULL,
      message    TEXT,
      fetched_at BIGINT NOT NULL,
      offer_count BIGINT NOT NULL DEFAULT 0, blocked_kind TEXT, fresh_offers_found BIGINT NOT NULL DEFAULT 0, cached_offers_available BIGINT NOT NULL DEFAULT 0, extras_json TEXT,
      PRIMARY KEY (vn_id, provider)
    );
CREATE TABLE IF NOT EXISTS vn_stock_alias (
      vn_id       TEXT NOT NULL,
      alias_term  TEXT NOT NULL,
      created_at  BIGINT NOT NULL DEFAULT 0,
      PRIMARY KEY (vn_id, alias_term)
    );
CREATE TABLE IF NOT EXISTS vn_stock_source (
      id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      vn_id      TEXT NOT NULL,
      release_id TEXT,
      provider   TEXT NOT NULL,
      url        TEXT NOT NULL,
      product_id TEXT,
      created_at BIGINT NOT NULL DEFAULT 0,
      updated_at BIGINT NOT NULL DEFAULT 0,
      UNIQUE(vn_id, url)
    );
CREATE TABLE IF NOT EXISTS vn_title_resolve_cache (
      query      TEXT PRIMARY KEY,
      vn_id      TEXT NOT NULL,
      title      TEXT NOT NULL
    );
CREATE TABLE IF NOT EXISTS place_registry (
      id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name       TEXT    NOT NULL,
      name_ja    TEXT,
      kind       TEXT    NOT NULL DEFAULT 'shop',
      address    TEXT,
      lat        DOUBLE PRECISION,
      lng        DOUBLE PRECISION,
      url        TEXT,
      notes      TEXT,
      created_at BIGINT NOT NULL,
      updated_at BIGINT NOT NULL
    );
CREATE TABLE IF NOT EXISTS place_provider_link (
      place_id       BIGINT NOT NULL REFERENCES place_registry(id) ON DELETE CASCADE,
      provider_label TEXT    NOT NULL,
      PRIMARY KEY (place_id, provider_label)
    );
CREATE TABLE IF NOT EXISTS stock_batch_job (
      id           TEXT PRIMARY KEY,
      label        TEXT NOT NULL,
      total        BIGINT NOT NULL,
      done         BIGINT NOT NULL DEFAULT 0,
      current_item TEXT,
      errors_json  TEXT NOT NULL DEFAULT '[]',
      started_at   BIGINT NOT NULL,
      finished_at  BIGINT,
      cancelled    BIGINT NOT NULL DEFAULT 0,
      interrupted  BIGINT NOT NULL DEFAULT 0, label_code TEXT, label_params_json TEXT, current_item_code TEXT, current_item_params_json TEXT);
CREATE TABLE IF NOT EXISTS app_job_lock (
        name TEXT PRIMARY KEY,
        owner TEXT NOT NULL,
        expires_at BIGINT NOT NULL
      );

CREATE INDEX IF NOT EXISTS idx_collection_status ON collection(status);
CREATE INDEX IF NOT EXISTS idx_collection_updated ON collection(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_series_vn_vn ON series_vn(vn_id);
CREATE INDEX IF NOT EXISTS idx_vndb_cache_expires ON vndb_cache(expires_at);
CREATE INDEX IF NOT EXISTS idx_owned_release_release ON owned_release(release_id);
CREATE INDEX IF NOT EXISTS idx_vn_route_vn ON vn_route(vn_id, order_index);
CREATE INDEX IF NOT EXISTS idx_egs_game_median ON egs_game(median);
CREATE INDEX IF NOT EXISTS idx_vn_quote_vn ON vn_quote(vn_id);
CREATE INDEX IF NOT EXISTS idx_vn_staff_credit_sid ON vn_staff_credit(sid);
CREATE INDEX IF NOT EXISTS idx_vn_staff_credit_vn  ON vn_staff_credit(vn_id);
CREATE INDEX IF NOT EXISTS idx_vn_va_credit_sid ON vn_va_credit(sid);
CREATE INDEX IF NOT EXISTS idx_vn_va_credit_cid ON vn_va_credit(c_id);
CREATE INDEX IF NOT EXISTS idx_vn_va_credit_vn  ON vn_va_credit(vn_id);
CREATE INDEX IF NOT EXISTS idx_vn_activity_vn ON vn_activity(vn_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_steam_link_appid ON steam_link(appid);
CREATE INDEX IF NOT EXISTS idx_vn_game_log_vn ON vn_game_log(vn_id, logged_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_list_pinned ON user_list(pinned DESC, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_list_vn_vn   ON user_list_vn(vn_id);
CREATE INDEX IF NOT EXISTS idx_user_list_vn_list ON user_list_vn(list_id, order_index);
CREATE INDEX IF NOT EXISTS idx_vn_activity_occurred ON vn_activity(occurred_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_app_setting_audit_changed
      ON app_setting_audit(changed_at DESC);
CREATE INDEX IF NOT EXISTS idx_egs_game_egs_id ON egs_game(egs_id);
CREATE INDEX IF NOT EXISTS idx_staff_credit_index_vn ON staff_credit_index(vn_id);
CREATE INDEX IF NOT EXISTS idx_character_vn_index_vn ON character_vn_index(vn_id);
CREATE INDEX IF NOT EXISTS idx_release_resolution_cache_aspect
      ON release_resolution_cache(aspect_key);
CREATE INDEX IF NOT EXISTS idx_owned_release_aspect_override_aspect
      ON owned_release_aspect_override(aspect_key);
CREATE INDEX IF NOT EXISTS idx_shelf_display_slot_shelf
      ON shelf_display_slot(shelf_id, after_row, position);
CREATE INDEX IF NOT EXISTS idx_vn_aspect_override_aspect
      ON vn_aspect_override(aspect_key);
CREATE INDEX IF NOT EXISTS idx_vn_egs_link_egs ON vn_egs_link(egs_id);
CREATE INDEX IF NOT EXISTS idx_egs_vn_link_vn ON egs_vn_link(vn_id);
CREATE INDEX IF NOT EXISTS idx_release_resolution_cache_vn ON release_resolution_cache(vn_id, aspect_key);
CREATE INDEX IF NOT EXISTS idx_release_meta_cache_vn
      ON release_meta_cache(vn_id);
CREATE INDEX IF NOT EXISTS user_activity_occurred_at ON user_activity (occurred_at DESC);
CREATE INDEX IF NOT EXISTS user_activity_kind ON user_activity (kind);
CREATE INDEX IF NOT EXISTS user_activity_entity ON user_activity (entity, entity_id);
CREATE INDEX IF NOT EXISTS idx_vn_tag_index_tag ON vn_tag_index(tag_id);
CREATE INDEX IF NOT EXISTS idx_vn_developer_index_pid ON vn_developer_index(producer_id);
CREATE INDEX IF NOT EXISTS idx_vn_publisher_index_pid ON vn_publisher_index(producer_id);
CREATE INDEX IF NOT EXISTS idx_vn_released   ON vn(released);
CREATE INDEX IF NOT EXISTS idx_vn_fetched_at ON vn(fetched_at);
CREATE INDEX IF NOT EXISTS idx_collection_finished_date ON collection(finished_date);
CREATE INDEX IF NOT EXISTS idx_saved_filter_position ON saved_filter(position);
CREATE UNIQUE INDEX IF NOT EXISTS idx_vn_staff_credit_unique
      ON vn_staff_credit(vn_id, sid, role);
CREATE INDEX IF NOT EXISTS idx_collection_custom_order ON collection(custom_order);
CREATE INDEX IF NOT EXISTS idx_collection_place_index_place ON collection_place_index(place);
CREATE INDEX IF NOT EXISTS idx_vn_language_index_lang ON vn_language_index(lang);
CREATE INDEX IF NOT EXISTS idx_vn_platform_index_platform ON vn_platform_index(platform);
CREATE INDEX IF NOT EXISTS idx_alicesoft_kobe_vn ON "alicenet_stock"(vn_id);
CREATE INDEX IF NOT EXISTS idx_vn_stock_offer_vn
      ON vn_stock_offer(vn_id, availability, price);
CREATE INDEX IF NOT EXISTS idx_vn_stock_offer_provider
      ON vn_stock_offer(provider, fetched_at);
CREATE INDEX IF NOT EXISTS idx_vn_stock_provider_status_vn
      ON vn_stock_provider_status(vn_id, fetched_at);
CREATE INDEX IF NOT EXISTS idx_vn_stock_source_vn
      ON vn_stock_source(vn_id, provider);
CREATE INDEX IF NOT EXISTS idx_vn_stock_offer_vn_avail
      ON vn_stock_offer(vn_id, availability)
      WHERE availability IN ('in_stock', 'limited');
CREATE INDEX IF NOT EXISTS idx_vn_stock_offer_fetched_at
      ON vn_stock_offer(fetched_at DESC);
CREATE INDEX IF NOT EXISTS idx_alicesoft_kobe_unmatched
      ON "alicenet_stock"(last_matched_at, code)
      WHERE vn_id IS NULL AND egs_id IS NULL AND vn_match_source IS NULL;
CREATE INDEX IF NOT EXISTS idx_alicesoft_kobe_no_vndb
      ON "alicenet_stock"(last_matched_at, code)
      WHERE vn_match_source = 'none' AND vn_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_collection_favorite
      ON collection(vn_id)
      WHERE favorite = 1;
CREATE INDEX IF NOT EXISTS idx_collection_user_rating
      ON collection(user_rating)
      WHERE user_rating IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_owned_release_dumped
      ON owned_release(vn_id)
      WHERE dumped = 1;
CREATE INDEX IF NOT EXISTS idx_collection_dumped
      ON collection(vn_id)
      WHERE dumped = 1;
CREATE INDEX IF NOT EXISTS idx_place_registry_name ON place_registry(LOWER(name));
CREATE INDEX IF NOT EXISTS idx_place_provider_link_label ON place_provider_link(provider_label);
CREATE INDEX IF NOT EXISTS idx_alicesoft_kobe_title
      ON "alicenet_stock"(title);
CREATE INDEX IF NOT EXISTS idx_alicesoft_kobe_egs_resolve
      ON "alicenet_stock"(code)
      WHERE vn_id IS NOT NULL AND egs_id IS NULL AND egs_match_source IS NULL;
CREATE INDEX IF NOT EXISTS idx_vn_stock_offer_location_branch
      ON vn_stock_offer(location_branch, availability, vn_id);
CREATE INDEX IF NOT EXISTS idx_vn_stock_offer_location_label
      ON vn_stock_offer(location_label, availability, vn_id);
CREATE INDEX IF NOT EXISTS idx_stock_batch_job_started
      ON stock_batch_job(started_at DESC);
CREATE INDEX IF NOT EXISTS idx_alicenet_vn ON alicenet_stock(vn_id);
CREATE INDEX IF NOT EXISTS idx_alicenet_unmatched
      ON alicenet_stock(last_matched_at, code)
      WHERE vn_id IS NULL AND egs_id IS NULL AND vn_match_source IS NULL;
CREATE INDEX IF NOT EXISTS idx_alicenet_no_vndb
      ON alicenet_stock(last_matched_at, code)
      WHERE vn_match_source = 'none' AND vn_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_alicenet_title
      ON alicenet_stock(title);
CREATE INDEX IF NOT EXISTS idx_alicenet_egs_resolve
      ON alicenet_stock(code)
      WHERE vn_id IS NOT NULL AND egs_id IS NULL AND egs_match_source IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_vn_va_credit_unique
          ON vn_va_credit(vn_id, c_id, sid, COALESCE(aid, -1), COALESCE(note, ''), COALESCE(va_lang, ''));
CREATE INDEX IF NOT EXISTS idx_app_job_lock_expiry ON app_job_lock(expires_at);

CREATE TABLE IF NOT EXISTS schema_migration (
      version TEXT PRIMARY KEY,
      applied_at BIGINT NOT NULL
    );
INSERT INTO schema_migration (version, applied_at)
      VALUES ('0001_baseline', (EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::BIGINT)
      ON CONFLICT (version) DO NOTHING;

COMMIT;
