-- Preserve malformed historical JSON without exposing it to runtime decoders.
BEGIN;

CREATE TABLE IF NOT EXISTS postgres_json_quarantine (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name     TEXT NOT NULL,
  column_name    TEXT NOT NULL,
  source_rowid   BIGINT NOT NULL,
  raw_kind       TEXT NOT NULL,
  raw_value      TEXT NOT NULL,
  quarantined_at BIGINT NOT NULL,
  UNIQUE (table_name, column_name, source_rowid)
);

CREATE INDEX IF NOT EXISTS idx_postgres_json_quarantine_source
  ON postgres_json_quarantine(table_name, column_name, source_rowid);

COMMIT;
