BEGIN;

CREATE TABLE IF NOT EXISTS physical_bundle (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  anchor_vn_id TEXT NOT NULL,
  anchor_release_id TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  UNIQUE (anchor_vn_id, anchor_release_id),
  FOREIGN KEY (anchor_vn_id, anchor_release_id)
    REFERENCES owned_release(vn_id, release_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS physical_bundle_member (
  bundle_id BIGINT NOT NULL REFERENCES physical_bundle(id) ON DELETE CASCADE,
  vn_id TEXT NOT NULL,
  release_id TEXT NOT NULL,
  position INTEGER NOT NULL,
  PRIMARY KEY (bundle_id, vn_id, release_id),
  UNIQUE (vn_id, release_id),
  FOREIGN KEY (vn_id, release_id)
    REFERENCES owned_release(vn_id, release_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_physical_bundle_member_order
  ON physical_bundle_member(bundle_id, position);

COMMIT;
